import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { CheckCircle2 } from 'lucide-react'
import { errorMessage } from '@/api/client'
import { ledgerApi } from '@/api/endpoints'
import type { SourceType } from '@/api/types'
import { PageHeader } from '@/components/layout/AppLayout'
import { Badge } from '@/components/ui/Badge'
import { Card } from '@/components/ui/Card'
import { Input, Select } from '@/components/ui/Field'
import { EmptyState, ErrorState, PageLoader } from '@/components/ui/PageLoader'
import { Table, TD, TH, THead, TR } from '@/components/ui/Table'
import { formatDate, formatMoney, titleCase } from '@/lib/utils'

const sourceTone: Record<SourceType, 'success' | 'warning' | 'info' | 'neutral'> = {
  INVOICE: 'success',
  BILL: 'warning',
  PAYMENT: 'info',
  MANUAL: 'neutral',
}

export function LedgerPage() {
  const [sourceType, setSourceType] = useState<SourceType | ''>('')
  const [from, setFrom] = useState('')
  const [to, setTo] = useState('')

  const { data, isLoading, isError, error } = useQuery({
    queryKey: ['ledger', sourceType, from, to],
    queryFn: () =>
      ledgerApi.search({
        sourceType: sourceType || undefined,
        from: from || undefined,
        to: to || undefined,
        size: 100,
      }),
  })

  const entries = data?.content ?? []

  return (
    <>
      <PageHeader
        title="General Ledger"
        description="Every journal entry generated by the system. Entries are immutable — corrections are made with new entries, never by editing history."
      />

      <div className="mb-4 flex flex-wrap items-end gap-3">
        <div>
          <label className="mb-1 block text-[10px] font-medium text-muted-ink uppercase">
            Source
          </label>
          <Select
            value={sourceType}
            onChange={(e) => setSourceType(e.target.value as SourceType | '')}
            className="w-44"
          >
            <option value="">All sources</option>
            <option value="INVOICE">Invoices</option>
            <option value="BILL">Bills</option>
            <option value="PAYMENT">Payments</option>
            <option value="MANUAL">Manual</option>
          </Select>
        </div>
        <div>
          <label className="mb-1 block text-[10px] font-medium text-muted-ink uppercase">From</label>
          <Input type="date" value={from} onChange={(e) => setFrom(e.target.value)} className="w-44" />
        </div>
        <div>
          <label className="mb-1 block text-[10px] font-medium text-muted-ink uppercase">To</label>
          <Input type="date" value={to} onChange={(e) => setTo(e.target.value)} className="w-44" />
        </div>
      </div>

      {isLoading ? (
        <Card>
          <PageLoader />
        </Card>
      ) : isError ? (
        <Card>
          <ErrorState message={errorMessage(error)} />
        </Card>
      ) : entries.length === 0 ? (
        <Card>
          <EmptyState
            title="No journal entries yet"
            description="Post an invoice or a bill and the resulting entry will appear here automatically."
          />
        </Card>
      ) : (
        <div className="space-y-3">
          {entries.map((entry) => (
            <Card key={entry.id} className="overflow-hidden">
              <div className="flex flex-wrap items-center justify-between gap-2 border-b border-lilac-200 bg-lilac-50 px-4 py-2.5">
                <div className="flex flex-wrap items-center gap-3">
                  <span className="tabular text-sm font-semibold text-plum-800">
                    {entry.entryNo}
                  </span>
                  <Badge tone={sourceTone[entry.sourceType]}>{titleCase(entry.sourceType)}</Badge>
                  <span className="text-sm text-muted-ink">{entry.narration}</span>
                </div>
                <div className="flex items-center gap-3 text-xs text-muted-ink">
                  <span>{entry.journalCode}</span>
                  <span>{formatDate(entry.entryDate)}</span>
                  {entry.balanced && (
                    <span className="inline-flex items-center gap-1 rounded-full bg-emerald-50 px-2 py-0.5 font-medium text-emerald-700 ring-1 ring-emerald-600/20 ring-inset">
                      <CheckCircle2 className="h-3 w-3" />
                      Balanced
                    </span>
                  )}
                </div>
              </div>

              <Table>
                <THead>
                  <tr>
                    <TH className="w-24">Code</TH>
                    <TH>Account</TH>
                    <TH>Contact</TH>
                    <TH className="text-right">Debit</TH>
                    <TH className="text-right">Credit</TH>
                  </tr>
                </THead>
                <tbody>
                  {entry.lines.map((l) => (
                    <TR key={l.id}>
                      <TD className="tabular text-muted-ink">{l.accountCode}</TD>
                      <TD>{l.accountName}</TD>
                      <TD className="text-muted-ink">{l.contactName ?? '—'}</TD>
                      <TD className="tabular text-right">
                        {Number(l.debit) > 0 ? formatMoney(l.debit) : ''}
                      </TD>
                      <TD className="tabular text-right">
                        {Number(l.credit) > 0 ? formatMoney(l.credit) : ''}
                      </TD>
                    </TR>
                  ))}
                  <tr className="bg-lilac-50/70 font-semibold">
                    <TD colSpan={3} className="text-right text-xs tracking-wide uppercase">
                      Total
                    </TD>
                    <TD className="tabular text-right">{formatMoney(entry.totalDebit)}</TD>
                    <TD className="tabular text-right">{formatMoney(entry.totalCredit)}</TD>
                  </tr>
                </tbody>
              </Table>
            </Card>
          ))}
        </div>
      )}
    </>
  )
}
